# Generated by Django 2.2.14 on 2020-07-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_customtext_jhfhjgjhg'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='tests',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
